# Generated by Django 5.1.1 on 2024-09-25 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0002_formdata_occasion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formdata',
            name='occasion',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
